version: "3"

services:

  notices-server:
    build: ./notices-server
    command: gunicorn run:app -w 2 --threads 2 -b 0.0.0.0:8000
    container_name: notices-server
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./notices-server:/app